# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 10:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='searchinCar',
            new_name='searchingCar',
        ),
    ]
