# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20160508_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='nam2e',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
