# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 08:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0008_auto_20160831_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='open',
            field=models.BooleanField(default=False),
        ),
    ]
