# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('kind', models.CharField(max_length=64)),
                ('seating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('date', models.DateField()),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('departTime', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ApplyAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('state', models.CharField(default='1', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CommentAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('announcement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='announcements.Announcement')),
            ],
        ),
        migrations.CreateModel(
            name='StopAnnouncement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop', models.CharField(max_length=256)),
                ('sequence', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='announcements.Announcement')),
            ],
        ),
    ]
