# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 11:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0002_auto_20160502_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='kind',
            field=models.CharField(choices=[('offer', 'Offer'), ('demand', 'Demand')], max_length=64),
        ),
    ]
