# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-31 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_auto_20160829_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
