# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-02 14:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplyRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creationDate', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
                ('state', models.CharField(default='1', max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CommentRoute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=128)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
            ],
        ),
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('departTime', models.CharField(max_length=64)),
                ('returnTime', models.CharField(max_length=64)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=256)),
                ('destination', models.CharField(max_length=256)),
                ('visibility', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('kind', models.CharField(max_length=64)),
                ('seating', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('creationMoment', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User')),
            ],
        ),
        migrations.AddField(
            model_name='day',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
        migrations.AddField(
            model_name='commentroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
        migrations.AddField(
            model_name='commentroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
        migrations.AddField(
            model_name='applyroute',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routes.Route'),
        ),
        migrations.AddField(
            model_name='applyroute',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.User'),
        ),
    ]
