# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-08 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0002_stoproute'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='kind',
            field=models.CharField(choices=[('offer', 'Offer'), ('demand', 'Demand')], max_length=64),
        ),
    ]
