# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-26 11:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0004_auto_20160623_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='day',
            options={'ordering': ['-day']},
        ),
    ]
