# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-29 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0006_auto_20160826_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
